apiVersion: v1
kind: Service
metadata:
  name: ${name}
  namespace: ${namespace}
  labels:
    app: ${app_label}
spec:
  selector:
    app: ${app_label}
  ports:
    - protocol: TCP
      port: ${service_port}
      targetPort: ${container_port}
  type: ${service_type}