apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ekcape-prometheus-stc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-pvc
  namespace: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ekcape-prometheus-stc  # Reference to the StorageClass


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-pvc
  namespace: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ekcape-prometheus-stc


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pushgateway-pvc
  namespace: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ekcape-prometheus-stc